baseURL = "https://macchioni.cc/"
languageCode = "en-us"
title = "Piero Macchioni"
theme = "hugo-lithium-theme"
rssLimit = 15

[Params]
  Author = "Piero Macchioni"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"
    singles = "/:title/"

 [sitemap]
    changefreq = "weekly"
    priority = 0.5


[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[twitter]
  card = "Summary"
  site = "@leibniz"
  title = "Title"
  description = "Description"
  image = "https://d33wubrfki0l68.cloudfront.net/9896fca54bdb842292671cbacb3353a18085ebf0/2ed03/images/piero-macchioni-bws.jpg"