baseURL = "https://macchioni.in/"
languageCode = "en-us"
title = "Piero Macchioni"
theme = "hugo-lithium-theme"
rssLimit = 15

[Params]
  Author = "Piero Macchioni"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"
    singles = "/:title/"

 [sitemap]
    changefreq = "weekly"
    priority = 0.5


[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"